config/routes.rb
Rails.application.routes.draw do



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'

  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'
  }
  devise_scope :user do
      get '/users/sign_out' => 'users/sessions#destroy'
       # post '/registration' => 'users/registrations#create'
    # get '/sign_out' => 'users/sessions#destroy'
    # delete '/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'questions' => 'makeq#create'

  # resources :questions do
  # end
  resources :root do
  end
  resources :makeq do
  end


  resources :question_lists, only: [:index, :show,:create, :update] do
     # resources :favorites, only: [:create, :destroy]
     # resources :answears, only: [:create, :update]
  end
  post '/question_lists/:id' => 'question_lists#create'

  get 'question_lists/:id/edit' => 'question_lists#edit', as: 'edit_answear'
  patch 'question_lists/:id/edit' => 'question_lists#update_answear', as: 'update_answear'


  get 'answears/:answear_id' => 'answears#show', as: "answears_kobetsu"
  post '/answears/:answear_id' => 'replies#create'
  delete '/answears/:answear_id' => 'replies#destroy'


  resources :question_lists, only: [:show,] do
    resource :favorites, only: [:create, :destroy]
  end

   post '/answears/:answear_id/favorites' => 'favorites#create', as: 'favorites'
   delete '/answears/:answear_id/favorites'=> 'favorites#destroy', as: 'favorites_cancel'

  # resources :question_list do

  # end

  root 'root#top'

  post 'questions' => 'makeq#create'

  # get '/index' => 'root/index'

   get '/top' => 'root#top'
   get 'rule' => 'root#rule'

   get '/' => 'root#top'

   get '/logout', to: 'sessions#destroy'

   resources :users, only: [:show]
   patch '/users/:id' => 'users#update'

   # get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answear.rb
class Answear < ApplicationRecord
	belongs_to :user
	belongs_to :question
	# validates :final_answear, presence: true
	# validates :answear_text, presence: true, length: { minimum: 8}
	has_many :favorites, dependent: :destroy
	has_many :replies, dependent: :destroy


    def favorited_by?(user)
       favorites.where(user_id: user.id).exists?
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :answear
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answears, dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :user
    belongs_to :answear
end

app/models/rollmodeltest.rb
class Rollmodeltest < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :answears, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :replies, dependent: :destroy
  validates :user_name, presence: true

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      if auth.provider == "twitter"
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        user_name:  auth.info.name,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
      else
        user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        user_name:  "No name(Please edit.)",
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
      end
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/makeq_controller.rb
class MakeqController < ApplicationController
	  before_action :post_params
    before_action :authenticate_user!
    before_action :authenticate_admin_user!
  def index
  	@questions = Question.all
  end

  def edit
  	@question = Question.find(params[:id])
  end

  def destroy
  		question = Question.find(params[:id])
        question.destroy
        redirect_to '/makeq'
  end
  def show
    @question = Question.find(params[:id])
    @answears = Answear.where(question_id: params[:id]).all
  end

  def create
    question = Question.new(post_params)
    question.save
    redirect_to '/makeq'
  end


  def new
    @question = Question.new
  end

  def update
  	question = Question.find(params[:id])
    question.update(post_params)
    redirect_to '/makeq'
  end

      private
 
    def post_params
          params.fetch(:question, {}).permit(:title, :explain, :koukai)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
		@questions = Question.all
		@user_count = User.all.count
	end

	def show
		redirect_to "/top"
	end
	def index
		@questions = Question.all
	end
	def about_us
	end

	def rule
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :contribution_count, only: [:show]
	before_action :user_params
  def show
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path
  end


  private
    def user_params
          params.fetch(:user, {}).permit(:user_name)
    end



  def contribution_count
  	user = User.find(params[:id])
  	answear_count = user.answears.count.to_i
  	favorites_count = 0
  	user.answears.each do |ans|
  		favorites_count = favorites_count + ans.favorites.count.to_i
  	end
  	@count = answear_count*5 + favorites_count
  end
end

app/helpers/answears_helper.rb
module AnswearsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.image
      "http://graph.facebook.com/#{user.uid}/picture?type=large" # facebookの画像があった場合
    else
      # 代替の何かを返す
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/make_answears_helper.rb
module MakeAnswearsHelper
end

app/helpers/makeq_helper.rb
module MakeqHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/makeq/delete.html.erb
<h1>MakeQ#delete</h1>
<p>Find me in app/views/makeq/delete.html.erb</p>

app/views/makeq/edit.html.erb
<h1>MakeQ#edit</h1>
<p>Find me in app/views/makeq/edit.html.erb</p>
<h1>編集画面</h1>
<%= form_for(@question, :url => {:action => :update}) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :explain %>
    <div>みんなの解答の公開設定  trueなら公開です！！！</div>
	<%= f.text_field :koukai %>
    <%= f.submit '保存' %>
<% end %>

<!-- , makeq_path(@question.id) -->

app/views/makeq/index.html.erb
<h1>管理画面</h1>
<p>Find me in app/views/makeq/index.html.erb</p>
<h1>投稿一覧</h1>
 <% @questions.each do |post| %>
    <p>タイトル</p>
    <%=link_to post.title, "/makeq/#{post.id}" %>
 <% end %>

app/views/makeq/new.html.erb
<h1>管理画面/新規作成</h1>
<p>Find me in app/views/makeq/add.html.erb</p>
<h1>新規投稿</h1>
<!-- form_for部分 -->
<%= form_for(@question) do |f| %>
 
    <h4>タイトル</h4>
    <%= f.text_field :title %>
 
    <h4>説明</h4>
    <%= f.text_area :explain %>
 
 
    <%= f.submit '投稿' %>
 
<% end %>

app/views/makeq/show.html.erb
showです
<h1>タイトル</h1>
<%= @question.title %>

<%= link_to "編集", edit_makeq_path(@question.id) %>
<%= link_to "削除", makeq_path(@question.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>


<div>現状の解答集<div>
<% @answears.each do |answear| %>
    <p><%= "答えの数値  :  #{answear.final_answear}" %></p>
    <p><%= "導出過程  :   #{answear.answear_text}" %></p>
<% end %>

app/views/questions/index.html.erb
<h1>Questions#index</h1>
<p>Find me in app/views/questions/index.html.erb</p>

app/views/root/index.html.erb
index


<h1>投稿一覧</h1>
 <% @questions.each do |post| %>
    <p>タイトル</p>
    <%=link_to post.title, "/makeq/#{post.id}" %>
 <% end %>

app/views/root/rule.html.erb
<div class = "page-title-container">
<div class = "page-title">フェルミDBのルール!</div>
</div>
<div class = "container-answears">
	<p>
		当サイトは、フェルミ推定をはじめとするいわゆる「答えのない問題」へ、誰でも気軽に答えを投稿できる<span class = "red">ユーザー参加型</span>で、結論や思考法を評価することを目的としたメディアサイトです。<br>
		運営者については<a href = "/about_us">About us</a>をご覧ください。
	</p>
</div>
<div class = "container-rule">
	<p>
		基本ルールです。
	</p>
	<p>
		まず、問題が出題される際に同時に「解答期限」が発行されます。ユーザーの皆様には皆様にはこの期限までに問題に解答していただきます。だいたい、出題から1週間ほどです。<br>
		「解答期限」を過ぎると、他の人の解答を閲覧することができます。そして、「いいね」と「反論」を投稿できます。<br>
		「解答期限」超過後4日の「投票期限」を迎えたタイミングで、もっともいいねが多い解答が優勝です！！
	</p>
	<p>
		<br><li class = "rule-kyocho">マイページについて</li><br>
		メニューのユーザー名をクリックして進んだ先にあります。
		<br>ユーザー名の変更とユーザーポイントである「Contribution」の確認ができます。<br>他の人のステータスも確認することができます。
	</p>
	<p>
		<br><li class = "rule-kyocho">「ユーザーポイント」について</li><br>
		マイページの「Contribution」が、各ユーザーの所持ポイントとなります。<br>

	</p>
	<p>
		問題への解答1つごとに+5pt,解答がいいねされるごとに１つにつき+1ptされます。
	</p>
</div>

app/views/root/top.html.erb
<div class = "page-title-container">
	<div class = "page-title">
		Top page
	</div>
</div>

<h3>現在公開中の問題一覧</h3>
<div class = "question-container">
 <% @questions.each do |post| %>
 	<div class = "q-list-box">
    	<div class = "taitoru">タイトル</div>
    	<div class = "question-title">
    		<%=link_to post.title, "/question_lists/#{post.id}", :style=>"color:#998a58;" %>
    	</div>
    	<div class = "question-explain">
    		<%= post.explain  %>
    	</div>
        <div class = "answear_count">
            <%= "現在の解答者数: #{post.answears.count}" %>
        </div>
        <div class = "created_at">
            <%= "created_at: #{post.created_at}" %>
        </div>
    </div>
 <% end %>
</div>
<div class = "taitoru">
    <%= "現在の登録者数...#{@user_count} 人!!いっぱいいますね!!"%>
</div>
<button type="button" class="btn btn-social btn-tw"><i class="fa icon-twitter"></i> <a href="https://twitter.com/share?url=https://fermidbk.herokuapp.com&text=超難問に挑戦します！" rel="nofollow" target="_blank">ツイートする</a></button>
<p>
	<%= link_to "ルール", "/rule", :style=>"color:orange;" %>
</p>

<p>
<%= link_to "About us", "/about_us", :style=>"color:orange;" %>
</p>