config/routes.rb
Rails.application.routes.draw do



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'

  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'
  }
  devise_scope :user do
      get '/users/sign_out' => 'users/sessions#destroy'
       # post '/registration' => 'users/registrations#create'
    # get '/sign_out' => 'users/sessions#destroy'
    # delete '/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'questions' => 'makeq#create'

  # resources :questions do
  # end
  resources :root do
  end
  resources :makeq do
  end


  resources :question_lists, only: [:index, :show,:create, :update] do
     # resources :favorites, only: [:create, :destroy]
     # resources :answears, only: [:create, :update]
  end
  post '/question_lists/:id' => 'question_lists#create'

  get 'question_lists/:id/edit' => 'question_lists#edit', as: 'edit_answear'
  patch 'question_lists/:id/edit' => 'question_lists#update_answear', as: 'update_answear'


  get 'answears/:answear_id' => 'answears#show', as: "answears_kobetsu"
  post '/answears/:answear_id' => 'replies#create'
  delete '/answears/:answear_id' => 'replies#destroy'


  resources :question_lists, only: [:show,] do
    resource :favorites, only: [:create, :destroy]
  end

   post '/answears/:answear_id/favorites' => 'favorites#create', as: 'favorites'
   delete '/answears/:answear_id/favorites'=> 'favorites#destroy', as: 'favorites_cancel'

  # resources :question_list do

  # end

  root 'root#top'

  post 'questions' => 'makeq#create'

  # get '/index' => 'root/index'

   get '/top' => 'root#top'
   get 'rule' => 'root#rule'

   get '/' => 'root#top'

   get '/logout', to: 'sessions#destroy'

   resources :users, only: [:show]
   patch '/users/:id' => 'users#update'

   # get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/question_lists_controller.rb
class QuestionListsController < ApplicationController
	before_action :authenticate_user!
	before_action :answear_params
	before_action :answear_count, only: [:show]
	before_action :current_user_answear, only: [:show]
	before_action :current_user_answear_count, only: [:show]
	before_action :answear_all, only: [:show]

	def index
		@questions = Question.all
	end
	def show
		@question = Question.find(params[:id])
		# @answear = current_user.answears.new(post_comment_params)
		@answear = Answear.new
		@a_count
		@current_user_answear
	end

	def new
		@answear = Answear.new
	end

	def create
    	question = Question.find(params[:id])
		answear = current_user.answears.new(answear_params)
		answear.question_id = question.id
    	answear.save
    	redirect_to question_list_path
  	end
  	# :question_list_id

  	def edit
  		question = Question.find(params[:id])
  		answears_q = current_user.answears.all
  		@answear = answears_q.where(question_id: question.id).first
  	end

  	def update_answear
  		question = Question.find(params[:id])
  		answears_q = current_user.answears.all
  		answear = answears_q.where(question_id: question.id).first
  		answear.update(answear_params)
  		redirect_to question_list_path
  	end

  	def update
    	question = Question.find(params[:id])
    	answear = current_user.answears.where(question_id: question.id).first
    	answear.update(blog_params)
    	redirect_to question_lists_path
	end

		private

	def post_comment_params
		params.fetch(:answear,{}).permit(:answear_text, :final_answear, :user_id)
		params.fetch(:question, {}).permit(:title, :explain)
	end

	def answear_params
		params.fetch(:answear,{}).permit(:user_id,:question_id,:answear_text, :final_answear)
		# params.fetch(:question, {}).permit(:title, :explain)
	end

	def answear_count
		question = Question.find(params[:id])
		a_count = question.answears.length.to_i
		@a_count = a_count
	end

	def current_user_answear
		@current_user_answears = current_user.answears.where(question_id: params[:id]).all
	end

	def current_user_answear_count
		question = Question.find(params[:id])
		cuacarray = question.answears.where(user_id: current_user.id).all
		@current_user_answear_count = cuacarray.length
	end
	def answear_all
		question = Question.find(params[:id])
		@answear_all = question.answears.all
	end

end

app/helpers/question_lists_helper.rb
module QuestionListsHelper
end

app/views/question_lists/edit.html.erb
<div class = "page-title">解答編集画面</div>
<%= form_for @answear, url: update_answear_path do |f| %>
    <h4>ファイナルアンサー</h4>
    <%= f.text_field :final_answear %>
    <h4>導出過程</h4>
    <%= f.text_area :answear_text,rows:7 %>
    <%= f.submit '更新' %>
<% end %>

app/views/question_lists/index.html.erb
question/index

<h1>投稿一覧</h1>
 <% @questions.each do |post| %>
    <p>タイトル</p>
    <%=link_to post.title, "/question_lists/#{post.id}" %>
 <% end %>

app/views/question_lists/show.html.erb
<div class = "page-title">問題タイトル</div>
<%= @question.title %>
<div class = "q_explain">問題説明</div>
<p>
<%= @question.explain %>
</p>

<table>
<% if @question.koukai == "true" %>
        <% @answear_all.each do |answear_all| %>
            <div class="container-answears" id = "container-answears-js">
            <div class = "final-wrapper"><%= answear_all.final_answear %></div>
            <div class = "explain-wrapper"><%= answear_all.answear_text %></div>
            <% ans_user_name = User.where(id: answear_all.user_id).first.user_name %>
            <%= link_to "created_by : #{ans_user_name}", "/users/#{answear_all.user_id}", :style=>"color:black;" %>
        <!-- いいね機能でつ -->
            <% if answear_all.favorited_by?(current_user) %>
                <p>
                    <%= link_to favorites_cancel_path(answear_all), method: :delete, :style=>"color:pink;" do %>
                        <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                        <%= answear_all.favorites.count %> いいね
                    <% end %>
                </p>
            <% else %>
                <p>
                    <%= link_to favorites_path(answear_all), method: :post, answear_id: answear_all.id, :style=>"color:pink;" do %>
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                         <%= answear_all.favorites.count %> いいんじゃね
                    <% end %>
                </p>
            <% end %>
            <div class = "ans-link">
                <% idlink = answear_all.id %>
                <%= link_to "詳細へ!!!", "/answears/#{answear_all.id}", :style=>"color:white;" %>
            </div>
            </div>
        <% end %>
<% else %>
    <% if @current_user_answear_count == 0 %>
        <%= form_for @answear , url: {:controller => :question_lists, :action => :create} do |f| %>
        <h4>ファイナルアンサー</h4>
        <%= f.text_field :final_answear %>
        <h4>過程</h4>
        <%= f.text_area :answear_text,rows:7 %>
        <%= f.submit '投稿' %>
            <% if @answear.errors.any? %>
                <p>エラーでーす。</p>
            <% end %>
        <% end %>
    <% else %>
        <div class = "container-your-answear">
        <p>あなたの解答</p>
        <% @current_user_answears.each do |current_a| %>
            <div class = "finail-wrapper"><%= "答えの数値  :  #{current_a.final_answear}" %></div>
            <div class = "explain-wrapper"><%= "導出過程  :   #{current_a.answear_text}" %></div>
        <% end %>
        <%= link_to "編集する??", edit_answear_path, :style=>"color:orange;" %>
        </div>
        <div>他の人の解答...現在非公開です。解答期限までお待ちください。</div>
       <button type="button" class="btn btn-social btn-tw"><i class="fa icon-twitter"></i> <a href="https://twitter.com/share?url=https://fermidbk.herokuapp.com&text=解答しました!皆さんも解答しましょう！" rel="nofollow" target="_blank">ツイートする</a></button>
    <% end %>
<% end %>
</table>


<ol>
    <% @question.answears.each do |post_comment| %>
    <% end %>
</ol>
<p>
<%="現在の解答者数:#{@a_count}" %>
</p>