config/routes.rb
Rails.application.routes.draw do



  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'users/show'

  # devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations'
  }
  devise_scope :user do
      get '/users/sign_out' => 'users/sessions#destroy'
       # post '/registration' => 'users/registrations#create'
    # get '/sign_out' => 'users/sessions#destroy'
    # delete '/sign_out' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  post 'questions' => 'makeq#create'

  # resources :questions do
  # end
  resources :root do
  end
  resources :makeq do
  end


  resources :question_lists, only: [:index, :show,:create, :update] do
     # resources :favorites, only: [:create, :destroy]
     # resources :answears, only: [:create, :update]
  end
  post '/question_lists/:id' => 'question_lists#create'

  get 'question_lists/:id/edit' => 'question_lists#edit', as: 'edit_answear'
  patch 'question_lists/:id/edit' => 'question_lists#update_answear', as: 'update_answear'


  get 'answears/:answear_id' => 'answears#show', as: "answears_kobetsu"
  post '/answears/:answear_id' => 'replies#create'
  delete '/answears/:answear_id' => 'replies#destroy'


  resources :question_lists, only: [:show,] do
    resource :favorites, only: [:create, :destroy]
  end

   post '/answears/:answear_id/favorites' => 'favorites#create', as: 'favorites'
   delete '/answears/:answear_id/favorites'=> 'favorites#destroy', as: 'favorites_cancel'

  # resources :question_list do

  # end

  root 'root#top'

  post 'questions' => 'makeq#create'

  # get '/index' => 'root/index'

   get '/top' => 'root#top'
   get 'rule' => 'root#rule'

   get '/' => 'root#top'

   get '/logout', to: 'sessions#destroy'

   resources :users, only: [:show]
   patch '/users/:id' => 'users#update'

   # get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answear.rb
class Answear < ApplicationRecord
	belongs_to :user
	belongs_to :question
	# validates :final_answear, presence: true
	# validates :answear_text, presence: true, length: { minimum: 8}
	has_many :favorites, dependent: :destroy
	has_many :replies, dependent: :destroy


    def favorited_by?(user)
       favorites.where(user_id: user.id).exists?
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :answear
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
	has_many :answears, dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :user
    belongs_to :answear
end

app/models/rollmodeltest.rb
class Rollmodeltest < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_many :answears, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :replies, dependent: :destroy
  validates :user_name, presence: true

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      if auth.provider == "twitter"
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        user_name:  auth.info.name,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
      else
        user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        user_name:  "No name(Please edit.)",
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
      end
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/makeq_controller.rb
class MakeqController < ApplicationController
	  before_action :post_params
    before_action :authenticate_user!
    before_action :authenticate_admin_user!
  def index
  	@questions = Question.all
  end

  def edit
  	@question = Question.find(params[:id])
  end

  def destroy
  		question = Question.find(params[:id])
        question.destroy
        redirect_to '/makeq'
  end
  def show
    @question = Question.find(params[:id])
    @answears = Answear.where(question_id: params[:id]).all
  end

  def create
    question = Question.new(post_params)
    question.save
    redirect_to '/makeq'
  end


  def new
    @question = Question.new
  end

  def update
  	question = Question.find(params[:id])
    question.update(post_params)
    redirect_to '/makeq'
  end

      private
 
    def post_params
          params.fetch(:question, {}).permit(:title, :explain, :koukai)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
		@questions = Question.all
		@user_count = User.all.count
	end

	def show
		redirect_to "/top"
	end
	def index
		@questions = Question.all
	end
	def about_us
	end

	def rule
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :contribution_count, only: [:show]
	before_action :user_params
  def show
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path
  end


  private
    def user_params
          params.fetch(:user, {}).permit(:user_name)
    end



  def contribution_count
  	user = User.find(params[:id])
  	answear_count = user.answears.count.to_i
  	favorites_count = 0
  	user.answears.each do |ans|
  		favorites_count = favorites_count + ans.favorites.count.to_i
  	end
  	@count = answear_count*5 + favorites_count
  end
end

app/helpers/answears_helper.rb
module AnswearsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.image
      "http://graph.facebook.com/#{user.uid}/picture?type=large" # facebookの画像があった場合
    else
      # 代替の何かを返す
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/makeq_helper.rb
module MakeqHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>フェルミDB</title>
    <%= csrf_meta_tags %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125791998-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125791998-1');
</script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'track' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>



  </head>

  <body >
    <script type = "text/javascript">
$(function() {
$("container-answears").hover(
    function(){
        /* mouse enter の処理 */
        $(this).css("background", "#ffaaaa");
    }, 
    function(){
        /* mouse leave の処理 */
        $(this).css("background", "#222222");
    }
);
});

$(window).load(function(){
  $("container-answears").animate({
      'marginLeft': '500px'
    });
})
</script>
<style type="text/css">
/* スマホとタブレットのみに適用 */
@media screen and (max-width: 768px) {
  .navbar-container{
    width:100%;
    position:relative;
    left:0;
    transition:left .4s;
  }
}
</style>

    

     <header>
      <div class = "top-of-top">
        <div class = "head-name-left">
          彼方の解を探すメディア
        </div>
        <div class = "head-name-right">
          <%= link_to 'About us', '/about_us' %>
        </div>
      </div>
<!--       <hgroup> -->
      <div class = "second-top">
        <div class = "logo-container">
          <!-- <img class = "logo-image" src = "/logo.png" href = "/top"> -->
          <%= link_to image_tag('logo.png', :class => "logo-image"), "/top" %>
        </div>
        <div class = ""></div>
      </div>

        <div class = "navbar-container">
        <div class = "navbar-leftbar"></div>
        <ul class="jajaja">
          <div class = "navbar-rightbar">
            <div id="container-fluid">
              <ul class="navbar-header" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
                <% if user_signed_in? %>
                  <li class="icon-bar header-menues">
                    <div class = "glyphicon glyphicon-log-out"></div>
                    <%= link_to 'Sign out', users_sign_out_path, method: :get, :style=>"color:white;" %>
                  </li>
                  <li class="icon-bar header-menues">
        <!-- ↓ここにつきましては、5章の方で正しいroutingに書き直します。 -->
                    <div class = "glyphicon glyphicon-home"></div>
                    <%= link_to "マイページ", user_path(current_user.id), :style=>"color:white;"%>
                  </li>
                  <li class="icon-bar header-menues">
                    
                  </li>
                <% else %>
                  <li class="icon-bar header-menues">
                    <div class = "glyphicon glyphicon-user"></div>
                    <%= link_to "Registration", new_user_registration_path, :style=>"color:white;" %>
                  </li>
                  <li class="icon-bar header-menues" >
                    <div class = "glyphicon glyphicon-log-in"></div>
                    <%= link_to "Sign in", new_user_session_path, :style=>"color:white;" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </ul>
      </div>
<!--       </hgroup> -->
    </header>
    <div id = "wrap">
    <div class = "super-outer">
      <div class = "left-bar"></div>
      <div class = "main-content">
        <%= yield %>
      </div>
      <div class = "right-bar"></div>
    </div>
  </div>
  </body>
  <footer>
    <div class = "footer-wrapper">
      <div class = "copy-right">© Kawatthy</div>
      <div class = "footer-about-us">About us</div>
    </div>
  </footer>
</html>